name: sdgp_pawrescue
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/treatment.png
    - assets/injured.png
    - assets/animal_profiles.png
    - assets/medi_center.png